services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=fundify'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=arav'
      - 'TZ=Asia/Kolkata'
    ports:
      - '5432:5432'
